name: Deploy Backend to Azure App Service

# on:
#   push:
#     paths:
#       - 'todo-backend/**'
#       - '.github/workflows/backend-deploy.yml'
#     branches:
#       - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: todo-backend
        run: mvn clean package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # set in repo secrets
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: todo-backend/target/*.jar
