name: Reusable CI with E2E

on:
  workflow_call:
    inputs:
      e2e-grep:
        required: false
        description: 'Playwright grep pattern, e.g., @smoke or @regression'
        type: string

jobs:
  build-test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # BACKEND: Unit Test (H2)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test Backend (H2 in-memory)
        working-directory: ./todo-backend
        run: mvn test -Dspring.profiles.active=h2

      - name: Upload Backend Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: todo-backend/target/surefire-reports/

      # FRONTEND: Unit Test
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./todo-frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./todo-frontend
        run: npm test -- --ci --watchAll=false

      - name: Upload Frontend Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: todo-frontend/test-results/

      # #########################################
      # # BACKEND/FRONTEND START FOR E2E
      # #########################################
      # - name: Build frontend for E2E
      #   working-directory: ./todo-frontend
      #   run: npm run build

      # - name: Start backend (H2, detached)
      #   working-directory: ./todo-backend
      #   run: nohup mvn spring-boot:run -Dspring.profiles.active=h2 > ../../backend-e2e.log 2>&1 &

      # - name: Start frontend (detached)
      #   working-directory: ./todo-frontend
      #   run: nohup npx serve -s build -l 3000 > ../../frontend-e2e.log 2>&1 &

      # - name: Wait for backend to be ready
      #   run: |
      #     echo "Waiting for backend (localhost:8080)..."
      #     for i in {1..20}; do
      #       if curl --fail http://localhost:8080/actuator/health; then exit 0; fi
      #       sleep 3
      #     done
      #     echo "Backend not responding!"; exit 1

      # - name: Wait for frontend to be ready
      #   run: |
      #     echo "Waiting for frontend (localhost:3000)..."
      #     for i in {1..10}; do
      #       if curl --fail http://localhost:3000; then exit 0; fi
      #       sleep 3
      #     done
      #     echo "Frontend not responding!"; exit 1

      #########################################
      # E2E TESTS
      #########################################
      # Install dependencies at repo root so Playwright is available
      - name: Install root dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: |
          if [ -z "${{ inputs.e2e-grep }}" ]; then
            npx playwright test tests-e2e
          else
            npx playwright test tests-e2e --grep "${{ inputs.e2e-grep }}"
          fi

      - name: Upload Playwright E2E results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-e2e-report
          path: |
            tests-e2e/playwright-report/
            tests-e2e/test-results/
